### ISSUE TITLE
Add warp as a dependency

### ISSUE THREAD

**Issue by a-bakos** [a-bakos/gazebo-cms#5]
```toml
tokio = { version = "1.1.1", features = ["full"] }
warp = "0.3.5"
```
