### ISSUE TITLE
Add Yew and implement a basic front end page

### ISSUE THREAD

**Issue by a-bakos** [a-bakos/gazebo-cms#8]
- Install WebAssembly target: `rustup target add wasm32-unknown-unknown`
- Install [Trunk](https://trunkrs.dev/): `cargo install --locked trunk`
- Install [cargo generate](https://github.com/cargo-generate/cargo-generate): `cargo install cargo-generate`
- Option A) Starter template: `cargo generate --git https://github.com/yewstack/yew-trunk-minimal-template`

---

- Option B) Manual set up: `cargo new yew-app` ...
- Update `cargo.toml`:

```toml
[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
```

- Update `main.rs`

```rust
use yew::prelude::*;

#[function_component]
fn App() -> Html {
    let counter = use_state(|| 0);
    let onclick = {
        let counter = counter.clone();
        move |_| {
            let value = *counter + 1;
            counter.set(value);
        }
    };

    html! {
        <div>
            <button {onclick}>{ "+1" }</button>
            <p>{ *counter }</p>
        </div>
    }
}

fn main() {
    yew::Renderer::<App>::new().render();
}
```

- Create an `index.html`

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Yew App</title>
    </head>
</html>
```

---

- Run `trunk serve`
